pip install pycaret==3.3.2

pip install scikit-learn==1.4.2

In [1]:
import pandas as pd
import numpy as np

hire=pd.read_csv("hiredata.csv")

In [2]:
hire.head()

   YearsExperience EducationLevel  SkillsScore  CertificationCount  Hired
0                6    High School           88                   0      0
1                3    High School           50                   3      0
2               12            PhD           78                   2      1
3               14  Post-Graduate           63                   3      1
4               10    High School           99                   3      1

### GenAI-powered tools 
Can build a machine learning model with minimal coding. These are excellent to demonstrate in a training session because learners can see a complete data modelling workflow in just a few minute
1. Pycaret
- Cleans missing values
- Encodes categorical variables
- Scales data (if appropriate)
- Trains multiple algorithms
- Compares performance
- Selects the best model
**This is one of the easiest ways to demonstrate end-to-end modelling**
2.  H2O AutoML

  It automatically trains and compares many algorithms such as Gradient Boosting, Random Forest, XGBoost, and Stacked Ensembles.
  
  | Tool                     | Best For                | Coding Required | Time to First Model |
| ------------------------ | ----------------------- | --------------- | ------------------- |
| PyCaret                  | AutoML in Python        | Low             | 5–10 min            |
| H2O.ai Driverless AI     | Enterprise AutoML       | No/Low          | 5 min               |
| AutoGluon                | High-accuracy ML        | Low             | 10 min              |
| Microsoft Fabric AutoML  | Microsoft ecosystem     | No              | 5 min               |
| DataRobot                | Business users          | No              | 5 min               |
| Google Vertex AI AutoML  | Cloud ML                | No              | 10 min              |
| KNIME Analytics Platform | Drag-and-drop workflows | No              | 10 min              |

In [6]:
from pycaret.classification import *

hire = pd.read_csv("hiredata.csv")
setup(data=hire,
      target="Hired",
      session_id=123)

best_model = compare_models()

evaluate_model(best_model)

predict_model(best_model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelin…

,YearsExperience,EducationLevel,SkillsScore,CertificationCount,Hired,prediction_label,prediction_score
703,1,PhD,78,6,0,0,0.9759
380,7,Diploma,76,2,1,1,0.9297
723,0,Post-Graduate,90,5,0,0,0.9716
600,14,High School,70,1,1,1,0.9727
7,4,Graduate,43,0,0,0,0.9629
...,...,...,...,...,...,...,...
714,9,PhD,82,1,1,1,0.9375
138,7,High School,94,6,1,1,0.9670
988,6,PhD,69,2,1,1,0.9451
718,2,PhD,84,5,0,0,0.9519
136,11,Post-Graduate,43,0,0,0,0.9814


import sys
!{sys.executable} -m pip install pycaret

In [8]:
pip install h2o

Note: you may need to restart the kernel to use updated packages.Collecting h2o
  Downloading h2o-3.46.0.11-py2.py3-none-any.whl.metadata (2.1 kB)
Requirement already satisfied: requests in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from h2o) (2.33.1)
Collecting tabulate (from h2o)
  Downloading tabulate-0.10.0-py3-none-any.whl.metadata (40 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests->h2o) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests->h2o) (3.12)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests->h2o) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests->h2o) (2026.2.25)
Downloading h2o-3.46.0.11-py2.py3-none-any.whl (266.4 MB)
   ---------------------------------------- 0.0/266.4 MB ? eta -:--:--
   ---------------------------------------- 0.8/266.4 MB 3.4 MB/s eta 0:01:20
   ---------------------------------------- 1.6/266.4 MB 3.7 MB/s eta 0:01:13
   ---------------------------------------- 2.6/266.4 MB 4.3 MB/s eta 0:01:02
    --------------------------------------- 4.2/266.4 MB 4.9 MB/s eta 0:00:54
    --------------------------------------- 5.0/266.4 MB 4.7 MB/s eta 0:00:56
    --------------------------------------- 6.6/266.4 MB 5.2 MB/s eta 0:00:50
   - -------------------------------------- 8.4/266.4 MB 5.6 MB/s eta 0:00:47
   - -------------------------------------- 10.0/266.4 MB 5.9 MB/s eta 0:00:44
   - -------------------------------------- 11.8/266.4 MB 6.2 MB/s eta 0:00:42
   -- ------------------------------------- 13.4/266.4 MB 6.4 MB/s eta 0:00:40
   -- ------------------------------------- 15.2/266.4 MB 6.6 MB/s eta 0:00:39
   -- ------------------------------------- 16.8/266.4 MB 6.6 MB/s eta 0:00:38
   -- ------------------------------------- 18.4/266.4 MB 6.7 MB/s eta 0:00:38
   --- ------------------------------------ 20.2/266.4 MB 6.9 MB/s eta 0:00:36
   --- ------------------------------------ 21.0/266.4 MB 6.9 MB/s eta 0:00:36
   --- ------------------------------------ 21.2/266.4 MB 6.4 MB/s eta 0:00:39
   --- ------------------------------------ 21.5/266.4 MB 6.2 MB/s eta 0:00:40
   --- ------------------------------------ 21.8/266.4 MB 5.9 MB/s eta 0:00:42
   --- ------------------------------------ 22.3/266.4 MB 5.5 MB/s eta 0:00:44
   --- ------------------------------------ 22.8/266.4 MB 5.4 MB/s eta 0:00:45
   --- ------------------------------------ 23.6/266.4 MB 5.3 MB/s eta 0:00:46
   --- ------------------------------------ 24.1/266.4 MB 5.2 MB/s eta 0:00:47
   --- ------------------------------------ 24.9/266.4 MB 5.1 MB/s eta 0:00:48
   --- ------------------------------------ 25.7/266.4 MB 5.1 MB/s eta 0:00:48
   --- ------------------------------------ 26.0/266.4 MB 5.0 MB/s eta 0:00:49
   ---- ----------------------------------- 27.0/266.4 MB 4.9 MB/s eta 0:00:50
   ---- ----------------------------------- 27.5/266.4 MB 4.8 MB/s eta 0:00:50
   ---- ----------------------------------- 28.3/266.4 MB 4.8 MB/s eta 0:00:50
   ---- ----------------------------------- 29.4/266.4 MB 4.8 MB/s eta 0:00:50
   ---- ----------------------------------- 29.9/266.4 MB 4.7 MB/s eta 0:00:51
   ---- ----------------------------------- 29.9/266.4 MB 4.7 MB/s eta 0:00:51
   ---- ----------------------------------- 29.9/266.4 MB 4.7 MB/s eta 0:00:51
   ---- ----------------------------------- 30.9/266.4 MB 4.4 MB/s eta 0:00:54
   ---- ----------------------------------- 31.7/266.4 MB 4.4 MB/s eta 0:00:54
   ---- ----------------------------------- 33.0/266.4 MB 4.4 MB/s eta 0:00:53
   ----- ---------------------------------- 33.8/266.4 MB 4.4 MB/s eta 0:00:53
   ----- ---------------------------------- 34.3/266.4 MB 4.3 MB/s eta 0:00:54
   ----- ---------------------------------- 35.1/266.4 MB 4.3 MB/s eta 0:00:54
   ----- ---------------------------------- 36.2/266.4 MB 4.4 MB/s eta 0:00:53
   ----- ---------------------------------- 37.2/266.4 MB 4.4 MB/s eta 0:00:53
   ----- ---------------------------------- 38.3/266.4 MB 4.4 MB/s eta 0:00:53
   ----- ---------------------------------- 39.1/266.4 MB 4.3 MB/s eta 0:00:53
   ----- ---------------------------------- 39.8/266.4 MB 4.3 MB/s eta 0:00:53
   ------ --------------------------------- 40.4/266.4 MB 4.3 MB/s eta 0:00:53
   ------ --------------------------------- 41.4/266.4 MB 4.3 MB/s eta 0:00:53
   ------ --------------------------------- 42.7/266.4 MB 4.4 MB/s eta 0:00:52
   ------ --------------------------------- 43.8/266.4 MB 4.4 MB/s eta 0:00:51
   ------ --------------------------------- 45.1/266.4 MB 4.4 MB/s eta 0:00:51
   ------ --------------------------------- 46.1/266.4 MB 4.4 MB/s eta 0:00:50
   ------- -------------------------------- 47.4/266.4 MB 4.4 MB/s eta 0:00:50
   ------- -------------------------------- 48.5/266.4 MB 4.5 MB/s eta 0:00:49
   ------- -------------------------------- 48.8/266.4 MB 4.4 MB/s eta 0:00:50
   ------- -------------------------------- 48.8/266.4 MB 4.4 MB/s eta 0:00:50
   ------- -------------------------------- 49.8/266.4 MB 4.3 MB/s eta 0:00:51
   ------- -------------------------------- 50.9/266.4 MB 4.3 MB/s eta 0:00:50
   ------- -------------------------------- 52.2/266.4 MB 4.3 MB/s eta 0:00:50
   ------- -------------------------------- 53.0/266.4 MB 4.3 MB/s eta 0:00:50
   -------- ------------------------------- 54.0/266.4 MB 4.3 MB/s eta 0:00:49
   -------- ------------------------------- 55.1/266.4 MB 4.4 MB/s eta 0:00:49
   -------- ------------------------------- 56.4/266.4 MB 4.4 MB/s eta 0:00:48
   -------- ------------------------------- 57.7/266.4 MB 4.4 MB/s eta 0:00:48
   -------- ------------------------------- 59.0/266.4 MB 4.4 MB/s eta 0:00:47
   --------- ------------------------------ 60.6/266.4 MB 4.5 MB/s eta 0:00:46
   --------- ------------------------------ 61.9/266.4 MB 4.5 MB/s eta 0:00:46
   --------- ------------------------------ 63.4/266.4 MB 4.6 MB/s eta 0:00:45
   --------- ------------------------------ 65.0/266.4 MB 4.6 MB/s eta 0:00:44
   --------- ------------------------------ 66.1/266.4 MB 4.6 MB/s eta 0:00:44
   ---------- ----------------------------- 67.4/266.4 MB 4.6 MB/s eta 0:00:44
   ---------- ----------------------------- 68.7/266.4 MB 4.6 MB/s eta 0:00:43
   ---------- ----------------------------- 70.3/266.4 MB 4.7 MB/s eta 0:00:42
   ---------- ----------------------------- 71.6/266.4 MB 4.7 MB/s eta 0:00:42
   ---------- ----------------------------- 72.9/266.4 MB 4.7 MB/s eta 0:00:41
   ----------- ---------------------------- 74.7/266.4 MB 4.8 MB/s eta 0:00:41
   ----------- ---------------------------- 76.5/266.4 MB 4.8 MB/s eta 0:00:40
   ----------- ---------------------------- 77.9/266.4 MB 4.8 MB/s eta 0:00:39
   ----------- ---------------------------- 79.2/266.4 MB 4.9 MB/s eta 0:00:39
   ------------ --------------------------- 80.7/266.4 MB 4.9 MB/s eta 0:00:38
   ------------ --------------------------- 82.3/266.4 MB 4.9 MB/s eta 0:00:38
   ------------ --------------------------- 83.6/266.4 MB 4.9 MB/s eta 0:00:37
   ------------ --------------------------- 84.7/266.4 MB 4.9 MB/s eta 0:00:37
   ------------ --------------------------- 86.2/266.4 MB 5.0 MB/s eta 0:00:37
   ------------- -------------------------- 88.1/266.4 MB 5.0 MB/s eta 0:00:36
   ------------- -------------------------- 89.7/266.4 MB 5.0 MB/s eta 0:00:36
   ------------- -------------------------- 89.9/266.4 MB 5.0 MB/s eta 0:00:36
   ------------- -------------------------- 90.4/266.4 MB 5.0 MB/s eta 0:00:36
   ------------- -------------------------- 91.8/266.4 MB 5.0 MB/s eta 0:00:36
   ------------- -------------------------- 92.3/266.4 MB 4.9 MB/s eta 0:00:36
   ------------- -------------------------- 92.5/266.4 MB 4.9 MB/s eta 0:00:36
   -------------- ------------------------- 93.3/266.4 MB 4.9 MB/s eta 0:00:36
   -------------- ------------------------- 93.8/266.4 MB 4.9 MB/s eta 0:00:36
   -------------- ------------------------- 94.6/266.4 MB 4.9 MB/s eta 0:00:36
   -------------- ------------------------- 95.4/266.4 MB 4.8 MB/s eta 0:00:36
   -------------- ------------------------- 96.5/266.4 MB 4.8 MB/s eta 0:00:36
   -------------- ------------------------- 97.8/266.4 MB 4.9 MB/s eta 0:00:35
   -------------- ------------------------- 99.1/266.4 MB 4.9 MB/s eta 0:00:35
   --------------- ------------------------ 100.7/266.4 MB 4.9 MB/s eta 0:00:34
   --------------- ------------------------ 102.0/266.4 MB 4.9 MB/s eta 0:00:34
   --------------- ------------------------ 103.3/266.4 MB 4.9 MB/s eta 0:00:34
   --------------- ------------------------ 104.9/266.4 MB 4.9 MB/s eta 0:00:33
   --------------- ------------------------ 106.4/266.4 MB 5.0 MB/s eta 0:00:33
   ---------------- ----------------------- 107.7/266.4 MB 5.0 MB/s eta 0:00:32
   ---------------- ----------------------- 109.3/266.4 MB 5.0 MB/s eta 0:00:32
   ---------------- ----------------------- 110.9/266.4 MB 5.0 MB/s eta 0:00:31
   ---------------- ----------------------- 112.2/266.4 MB 5.0 MB/s eta 0:00:31
   ----------------- ---------------------- 113.8/266.4 MB 5.0 MB/s eta 0:00:31
   ----------------- ---------------------- 115.1/266.4 MB 5.1 MB/s eta 0:00:30
   ----------------- ---------------------- 116.1/266.4 MB 5.1 MB/s eta 0:00:30
   ----------------- ---------------------- 116.4/266.4 MB 5.0 MB/s eta 0:00:30
   ----------------- ---------------------- 117.4/266.4 MB 5.0 MB/s eta 0:00:30
   ----------------- ---------------------- 119.0/266.4 MB 5.0 MB/s eta 0:00:30
   ------------------ --------------------- 120.1/266.4 MB 5.0 MB/s eta 0:00:30
   ------------------ --------------------- 121.6/266.4 MB 5.1 MB/s eta 0:00:29
   ------------------ --------------------- 123.2/266.4 MB 5.1 MB/s eta 0:00:29
   ------------------ --------------------- 125.0/266.4 MB 5.1 MB/s eta 0:00:28
   ------------------- -------------------- 127.1/266.4 MB 5.1 MB/s eta 0:00:28
   ------------------- -------------------- 128.7/266.4 MB 5.2 MB/s eta 0:00:27
   ------------------- -------------------- 130.8/266.4 MB 5.2 MB/s eta 0:00:27
   ------------------- -------------------- 132.6/266.4 MB 5.2 MB/s eta 0:00:26
   -------------------- ------------------- 135.0/266.4 MB 5.3 MB/s eta 0:00:25
   -------------------- ------------------- 136.6/266.4 MB 5.3 MB/s eta 0:00:25
   -------------------- ------------------- 138.4/266.4 MB 5.3 MB/s eta 0:00:24
   --------------------- ------------------ 140.2/266.4 MB 5.4 MB/s eta 0:00:24
   --------------------- ------------------ 141.8/266.4 MB 5.4 MB/s eta 0:00:24
   --------------------- ------------------ 143.4/266.4 MB 5.4 MB/s eta 0:00:23
   --------------------- ------------------ 145.0/266.4 MB 5.4 MB/s eta 0:00:23
   --------------------- ------------------ 146.0/266.4 MB 5.4 MB/s eta 0:00:23
   ---------------------- ----------------- 147.3/266.4 MB 5.4 MB/s eta 0:00:23
   ---------------------- ----------------- 148.1/266.4 MB 5.4 MB/s eta 0:00:22
   ---------------------- ----------------- 148.1/266.4 MB 5.4 MB/s eta 0:00:22
   ---------------------- ----------------- 148.4/266.4 MB 5.3 MB/s eta 0:00:23
   ---------------------- ----------------- 148.6/266.4 MB 5.3 MB/s eta 0:00:23
   ---------------------- ----------------- 148.9/266.4 MB 5.3 MB/s eta 0:00:23
   ---------------------- ----------------- 149.2/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.2/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.4/266.4 MB 5.2 MB/s eta 0:00:23
   ---------------------- ----------------- 149.7/266.4 MB 4.7 MB/s eta 0:00:25
   ---------------------- ----------------- 149.9/266.4 MB 4.6 MB/s eta 0:00:26
   ---------------------- ----------------- 150.5/266.4 MB 4.6 MB/s eta 0:00:26
   ---------------------- ----------------- 151.3/266.4 MB 4.5 MB/s eta 0:00:26
   ---------------------- ----------------- 152.0/266.4 MB 4.5 MB/s eta 0:00:26
   ---------------------- ----------------- 152.8/266.4 MB 4.5 MB/s eta 0:00:26
   ----------------------- ---------------- 154.1/266.4 MB 4.4 MB/s eta 0:00:26
   ----------------------- ---------------- 155.5/266.4 MB 4.5 MB/s eta 0:00:25
   ----------------------- ---------------- 157.5/266.4 MB 4.6 MB/s eta 0:00:24
   ----------------------- ---------------- 159.4/266.4 MB 4.6 MB/s eta 0:00:24
   ------------------------ --------------- 161.7/266.4 MB 4.7 MB/s eta 0:00:23
   ------------------------ --------------- 163.8/266.4 MB 4.7 MB/s eta 0:00:22
   ------------------------ --------------- 166.2/266.4 MB 4.8 MB/s eta 0:00:22
   ------------------------- -------------- 169.3/266.4 MB 4.8 MB/s eta 0:00:21
   ------------------------- -------------- 171.7/266.4 MB 4.9 MB/s eta 0:00:20
   -------------------------- ------------- 174.3/266.4 MB 5.0 MB/s eta 0:00:19
   -------------------------- ------------- 176.4/266.4 MB 5.0 MB/s eta 0:00:18
   -------------------------- ------------- 179.0/266.4 MB 5.1 MB/s eta 0:00:18
   --------------------------- ------------ 181.1/266.4 MB 5.1 MB/s eta 0:00:17
   --------------------------- ------------ 183.2/266.4 MB 5.2 MB/s eta 0:00:17
   --------------------------- ------------ 185.6/266.4 MB 5.2 MB/s eta 0:00:16
   ---------------------------- ----------- 187.4/266.4 MB 5.3 MB/s eta 0:00:15
   ---------------------------- ----------- 189.5/266.4 MB 5.4 MB/s eta 0:00:15
   ---------------------------- ----------- 192.2/266.4 MB 5.4 MB/s eta 0:00:14
   ----------------------------- ---------- 194.8/266.4 MB 5.5 MB/s eta 0:00:14
   ----------------------------- ---------- 197.4/266.4 MB 5.5 MB/s eta 0:00:13
   ------------------------------ --------- 200.3/266.4 MB 5.6 MB/s eta 0:00:12
   ------------------------------ --------- 202.9/266.4 MB 5.6 MB/s eta 0:00:12
   ------------------------------ --------- 205.5/266.4 MB 5.7 MB/s eta 0:00:11
   ------------------------------- -------- 207.6/266.4 MB 5.8 MB/s eta 0:00:11
   ------------------------------- -------- 209.7/266.4 MB 5.8 MB/s eta 0:00:10
   ------------------------------- -------- 209.7/266.4 MB 5.8 MB/s eta 0:00:10
   ------------------------------- -------- 209.7/266.4 MB 5.8 MB/s eta 0:00:10
   ------------------------------- -------- 210.8/266.4 MB 5.7 MB/s eta 0:00:10
   ------------------------------- -------- 211.3/266.4 MB 5.7 MB/s eta 0:00:10
   -------------------------------- ------- 213.6/266.4 MB 5.8 MB/s eta 0:00:10
   -------------------------------- ------- 215.5/266.4 MB 5.8 MB/s eta 0:00:09
   -------------------------------- ------- 217.6/266.4 MB 5.8 MB/s eta 0:00:09
   -------------------------------- ------- 219.7/266.4 MB 5.9 MB/s eta 0:00:08
   --------------------------------- ------ 221.8/266.4 MB 5.9 MB/s eta 0:00:08
   --------------------------------- ------ 224.1/266.4 MB 5.9 MB/s eta 0:00:08
   --------------------------------- ------ 226.2/266.4 MB 6.0 MB/s eta 0:00:07
   ---------------------------------- ----- 228.3/266.4 MB 6.0 MB/s eta 0:00:07
   ---------------------------------- ----- 230.7/266.4 MB 6.1 MB/s eta 0:00:06
   ----------------------------------- ---- 233.6/266.4 MB 6.2 MB/s eta 0:00:06
   ----------------------------------- ---- 235.9/266.4 MB 6.2 MB/s eta 0:00:05
   ----------------------------------- ---- 238.0/266.4 MB 6.3 MB/s eta 0:00:05
   ------------------------------------ --- 240.4/266.4 MB 6.3 MB/s eta 0:00:05
   ------------------------------------ --- 242.2/266.4 MB 6.3 MB/s eta 0:00:04
   ------------------------------------ --- 243.8/266.4 MB 6.3 MB/s eta 0:00:04
   ------------------------------------ --- 245.9/266.4 MB 6.4 MB/s eta 0:00:04
   ------------------------------------- -- 248.5/266.4 MB 6.4 MB/s eta 0:00:03
   ------------------------------------- -- 250.6/266.4 MB 6.5 MB/s eta 0:00:03
   ------------------------------------- -- 253.0/266.4 MB 6.5 MB/s eta 0:00:03
   -------------------------------------- - 255.3/266.4 MB 6.5 MB/s eta 0:00:02
   -------------------------------------- - 257.4/266.4 MB 6.5 MB/s eta 0:00:02
   -------------------------------------- - 259.5/266.4 MB 6.6 MB/s eta 0:00:02
   ---------------------------------------  261.6/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  264.0/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  265.8/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  266.3/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  266.3/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------  266.3/266.4 MB 6.6 MB/s eta 0:00:01
   ---------------------------------------- 266.4/266.4 MB 6.5 MB/s  0:00:45
Downloading tabulate-0.10.0-py3-none-any.whl (39 kB)
Installing collected packages: tabulate, h2o

   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   -------------------- ------------------- 1/2 [h2o]
   ---------------------------------------- 2/2 [h2o]

Successfully installed h2o-3.46.0.11 tabulate-0.10.0

  WARNING: The script tabulate.exe is installed in 'C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

import h2o
from h2o.automl import H2OAutoML

h2o.init()

data = h2o.import_file("hiredata.csv")

aml = H2OAutoML(max_models=20)

aml.train(y="Churn", training_frame=data)

aml.leader

pip install autogluon

In [13]:
from autogluon.tabular import TabularPredictor

predictor = TabularPredictor(label="Hired").fit("hiredata.csv")

predictor.leaderboard()

No path specified. Models will be saved in: "AutogluonModels\ag-20260702_090925"
Verbosity: 2 (Standard Logging)
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.10.20
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.26200
CPU Count:          14
Pytorch Version:    Can't import torch
CUDA Version:       Can't get cuda version from torch
Memory Avail:       1.74 GB / 15.47 GB (11.3%)
Disk Space Avail:   220.88 GB / 475.88 GB (46.4%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='extreme'  : New in v1.5: The state-of-the-art for tabular data. Massively better than 'best' on datasets <100000 samples by using new Tabular Foundation Models (TFMs) meta-learned on https://tabarena.ai: TabPFNv2, TabICL, Mitra, TabDPT, and TabM. Requires a GPU and `pip install autogluon.tabular[tabarena]` to install TabPFN, TabICL, and TabDPT.
	presets='best'     : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='best_v150': New in v1.5: Better quality than 'best' and 5x+ faster to train. Give it a try!
	presets='high'     : Strong accuracy with fast inference speed.
	presets='high_v150': New in v1.5: Better quality than 'high' and 5x+ faster to train. Give it a try!
	presets='good'     : Good accuracy with very fast inference speed.
	presets='medium'   : Fast training time, ideal for initial prototyping.
Loaded data from: hiredata.csv | Columns = 5 / 5 | Rows = 1200 -> 1200
Using hyperparameters preset: hyperparameters='default'
Beginning AutoGluon training ...
AutoGluon will save models to "C:\Users\Suyashi144893\Downloads\Intelligent Data Modelling using Python\AutogluonModels\ag-20260702_090925"
Train Data Rows:    1200
Train Data Columns: 4
Label Column:       Hired
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
	2 unique label values:  [0, 1]
	If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    2261.99 MB
	Train Data (Original)  Memory Usage: 0.10 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', [])    : 3 | ['YearsExperience', 'SkillsScore', 'CertificationCount']
		('object', []) : 1 | ['EducationLevel']
	Types of features in processed data (raw dtype, special dtypes):
		('category', []) : 1 | ['EducationLevel']
		('int', [])      : 3 | ['YearsExperience', 'SkillsScore', 'CertificationCount']
	0.1s = Fit runtime
	4 features in original data used to generate 4 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.1s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 960, Val Rows: 240
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0, mem=0.0/2.2 GB
	0.9417	 = Validation score   (accuracy)
	15.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0, mem=0.0/2.1 GB
	0.9417	 = Validation score   (accuracy)
	14.78s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=14, gpus=0
	0.9208	 = Validation score   (accuracy)
	15.76s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: RandomForestEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=14, gpus=0
	0.9208	 = Validation score   (accuracy)
	15.16s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: CatBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0
	0.9417	 = Validation score   (accuracy)
	33.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=14, gpus=0
	0.9208	 = Validation score   (accuracy)
	22.89s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=14, gpus=0
	0.9208	 = Validation score   (accuracy)
	17.72s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0, mem=0.0/1.7 GB
	Warning: Exception caused NeuralNetFastAI to fail during training... Skipping this model.
		[WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Detailed Traceback:
Traceback (most recent call last):
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py", line 2201, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py", line 2085, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 1114, in fit
    import torch
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\__init__.py", line 281, in <module>
    _load_dll_libraries()
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\__init__.py", line 264, in _load_dll_libraries
    raise err
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Fitting model: XGBoost ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0
	0.9417	 = Validation score   (accuracy)
	18.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0, mem=0.0/1.9 GB
	Warning: Exception caused NeuralNetTorch to fail during training... Skipping this model.
		[WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Detailed Traceback:
Traceback (most recent call last):
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py", line 2201, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\tabular\trainer\abstract_trainer.py", line 2085, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 1125, in fit
    out = self._fit(**kwargs)
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\tabular\models\tabular_nn\torch\tabular_nn_torch.py", line 184, in _fit
    try_import_torch()
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\autogluon\common\utils\try_import.py", line 159, in try_import_torch
    import torch
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\__init__.py", line 281, in <module>
    _load_dll_libraries()
  File "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\__init__.py", line 264, in _load_dll_libraries
    raise err
OSError: [WinError 1114] A dynamic link library (DLL) initialization routine failed. Error loading "C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\lib\site-packages\torch\lib\c10.dll" or one of its dependencies.
Fitting model: LightGBMLarge ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting with cpus=12, gpus=0, mem=0.1/1.8 GB
	0.9208	 = Validation score   (accuracy)
	22.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Failed to import torch or check CUDA availability!Please ensure you have the correct version of PyTorch installed by running `pip install -U torch`
	Fitting 1 model on all data | Fitting with cpus=14, gpus=0, mem=0.0/1.5 GB
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.9417	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 266.46s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 31124.6 rows/s (240 batch size)
Disabling decision threshold calibration for metric `accuracy` due to having fewer than 10000 rows of validation data for calibration, to avoid overfitting (240 rows).
	`accuracy` is generally not improved through threshold calibration. Force calibration via specifying `calibrate_decision_threshold=True`.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("C:\Users\Suyashi144893\Downloads\Intelligent Data Modelling using Python\AutogluonModels\ag-20260702_090925")

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.941667,accuracy,0.003073,33.414545,0.003073,33.414545,1,True,5
1,LightGBMXT,0.941667,accuracy,0.005698,15.691535,0.005698,15.691535,1,True,1
2,LightGBM,0.941667,accuracy,0.007468,14.784193,0.007468,14.784193,1,True,2
3,WeightedEnsemble_L2,0.941667,accuracy,0.007711,15.782519,0.002012,0.090984,2,True,10
4,XGBoost,0.941667,accuracy,0.017451,18.054651,0.017451,18.054651,1,True,8
5,LightGBMLarge,0.920833,accuracy,0.014744,22.865681,0.014744,22.865681,1,True,9
6,ExtraTreesGini,0.920833,accuracy,0.054006,22.889102,0.054006,22.889102,1,True,6
7,RandomForestGini,0.920833,accuracy,0.081831,15.758422,0.081831,15.758422,1,True,3
8,RandomForestEntr,0.920833,accuracy,0.083297,15.164856,0.083297,15.164856,1,True,4
9,ExtraTreesEntr,0.920833,accuracy,0.085256,17.723852,0.085256,17.723852,1,True,7

In [14]:
pip install streamlit pandas plotly seaborn matplotlib

Collecting streamlitNote: you may need to restart the kernel to use updated packages.

  Downloading streamlit-1.58.0-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: pandas in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (2.1.4)
Requirement already satisfied: plotly in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (6.8.0)
Requirement already satisfied: seaborn in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (0.13.2)
Requirement already satisfied: matplotlib in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (3.7.5)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.2.2-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (1.9.0)
Collecting cachetools<8,>=5.5 (from streamlit)
  Downloading cachetools-7.1.4-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: click<9,>=7.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (8.4.2)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.50-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging>=20 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (26.0)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (11.3.0)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Downloading pydeck-0.9.2-py2.py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: protobuf<8,>=3.20 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (6.33.6)
Requirement already satisfied: pyarrow>=7.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (20.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (2.33.1)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (9.1.4)
Collecting toml<2,>=0.10.1 (from streamlit)
  Downloading toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: starlette>=0.40.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (1.3.1)
Requirement already satisfied: uvicorn>=0.30.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (0.46.0)
Requirement already satisfied: httptools>=0.6.3 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (0.7.1)
Requirement already satisfied: anyio>=4.0.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (4.13.0)
Requirement already satisfied: python-multipart>=0.0.10 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (0.0.28)
Requirement already satisfied: websockets>=12.0.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (16.0)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from streamlit) (2.2.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Downloading watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: tzdata>=2022.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from pandas) (2026.1)
Requirement already satisfied: jinja2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=2.4.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.23.0)
Requirement already satisfied: colorama in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Downloading smmap-5.0.3-py3-none-any.whl.metadata (4.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests<3,>=2.27->streamlit) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.2.25)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from matplotlib) (1.3.2)
Requirement already satisfied: cycler>=0.10 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: exceptiongroup>=1.0.2 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from anyio>=4.0.0->streamlit) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (0.30.0)
Requirement already satisfied: six>=1.5 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: h11>=0.8 in c:\users\suyashi144893\appdata\local\anaconda3\envs\pytorch_env\lib\site-packages (from uvicorn>=0.30.0->streamlit) (0.16.0)
Downloading streamlit-1.58.0-py3-none-any.whl (9.2 MB)
   ---------------------------------------- 0.0/9.2 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.2 MB 2.8 MB/s eta 0:00:04
   ---- ----------------------------------- 1.0/9.2 MB 2.6 MB/s eta 0:00:04
   ------- -------------------------------- 1.8/9.2 MB 3.0 MB/s eta 0:00:03
   ----------- ---------------------------- 2.6/9.2 MB 3.0 MB/s eta 0:00:03
   -------------- ------------------------- 3.4/9.2 MB 3.2 MB/s eta 0:00:02
   ------------------ --------------------- 4.2/9.2 MB 3.3 MB/s eta 0:00:02
   --------------------- ------------------ 5.0/9.2 MB 3.4 MB/s eta 0:00:02
   ------------------------- -------------- 5.8/9.2 MB 3.4 MB/s eta 0:00:02
   ---------------------------- ----------- 6.6/9.2 MB 3.5 MB/s eta 0:00:01
   -------------------------------- ------- 7.6/9.2 MB 3.6 MB/s eta 0:00:01
   ------------------------------------ --- 8.4/9.2 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------- 9.2/9.2 MB 3.6 MB/s  0:00:02
Downloading altair-6.2.2-py3-none-any.whl (797 kB)
   ---------------------------------------- 0.0/797.6 kB ? eta -:--:--
   ---------------------------------------- 797.6/797.6 kB 4.3 MB/s  0:00:00
Downloading cachetools-7.1.4-py3-none-any.whl (16 kB)
Downloading gitpython-3.1.50-py3-none-any.whl (212 kB)
Downloading gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading pydeck-0.9.2-py2.py3-none-any.whl (11.3 MB)
   ---------------------------------------- 0.0/11.3 MB ? eta -:--:--
    --------------------------------------- 0.3/11.3 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.3 MB 3.2 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/11.3 MB 3.7 MB/s eta 0:00:03
   ------------ --------------------------- 3.4/11.3 MB 4.1 MB/s eta 0:00:02
   --------------- ------------------------ 4.5/11.3 MB 4.3 MB/s eta 0:00:02
   ------------------- -------------------- 5.5/11.3 MB 4.5 MB/s eta 0:00:02
   ----------------------- ---------------- 6.6/11.3 MB 4.6 MB/s eta 0:00:02
   -------------------------- ------------- 7.6/11.3 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 8.9/11.3 MB 4.7 MB/s eta 0:00:01
   ----------------------------------- ---- 10.0/11.3 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.3 MB 4.9 MB/s eta 0:00:01
   ---------------------------------------- 11.3/11.3 MB 4.8 MB/s  0:00:02
Downloading smmap-5.0.3-py3-none-any.whl (24 kB)
Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)
Downloading watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Installing collected packages: watchdog, toml, smmap, cachetools, pydeck, gitdb, gitpython, altair, streamlit

   ---------------------------------------- 0/9 [watchdog]
   ---------------------------------------- 0/9 [watchdog]
   -------- ------------------------------- 2/9 [smmap]
   ------------- -------------------------- 3/9 [cachetools]
   ----------------- ---------------------- 4/9 [pydeck]
   ----------------- ---------------------- 4/9 [pydeck]
   ----------------- ---------------------- 4/9 [pydeck]
   ---------------------- ----------------- 5/9 [gitdb]
   ---------------------- ----------------- 5/9 [gitdb]
   -------------------------- ------------- 6/9 [gitpython]
   -------------------------- ------------- 6/9 [gitpython]
   -------------------------- ------------- 6/9 [gitpython]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ------------------------------- -------- 7/9 [altair]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ----------------------------------- ---- 8/9 [streamlit]
   ---------------------------------------- 9/9 [streamlit]

Successfully installed altair-6.2.2 cachetools-7.1.4 gitdb-4.0.12 gitpython-3.1.50 pydeck-0.9.2 smmap-5.0.3 streamlit-1.58.0 toml-0.10.2 watchdog-6.0.0

  WARNING: The script watchmedo.exe is installed in 'C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script streamlit.exe is installed in 'C:\Users\Suyashi144893\AppData\Local\anaconda3\envs\pytorch_env\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.